### PR TITLE
Session decoding is done manually if Django returns an empty session

### PR DESCRIPTION
**Pull request by maxdore**

### CODE REVIEW

**Comment by jonashagstedt** [comment]
Thank you. Will review this as soon as I get a chance.

**Comment by cancan101** [comment]
Can you elaborate on why this is the right thing to do? Something seems wrong to me if even though Django won't decode the data we should.

**Comment by jonashagstedt** [comment]
The pull request broke in Py3.

**Comment by cancan101** [comment]
Right, but why this patch even to begin with?

**Comment by jonashagstedt** [comment]
Ah now that is a better question. 

@maxdore Can you provide a way to replicate this?

**Comment by maxdore** [comment]
I had this problem on a private project, I will try to replicate this on a fresh installation.

The solution is maybe a bit hacky, but I thought this problem occurs frequently (http://stackoverflow.com/questions/13146794/how-to-overcome-session-get-decoded-hash-check).

I will dig further in the problem and tell you more soon.

**Comment by jonashagstedt** [comment]
It's an interesting issue. I personally have never seen it, and that particular SO post has only been viewed 212 times over the last 2 years so it doesn't seem like it's that common.

That doesn't mean it should be disregarded of course, but it does sound like a bug with Django.

I guess you would still get the error even if you used the latest version (I rewrote a lot in `get_user`) yesterday.

If you do find out how to replicate this bug I would be interested in seeing it, though I think perhaps a bug should be reported on the Django bug tracker if you can replicate this.

**Comment by jonashagstedt** [comment]
I had to revert your pull request because it didn't work on Python 3.
I will update the README file to mention that PR should work with both Py2 and 3.

**Comment by cancan101** [comment]
This to me says to me we are doing something wrong if we are coding around django:
>decode method, which will return an empty dictionary if a calculated hash is different from an expected hash (it raises a SuspiciousOperation exception).

**Comment by jonashagstedt** [comment]
I do agree with @cancan101 on this one. 
It should behave closer to Django
But I would still like to see the issue if possible (as I am curious)

**Pull request merged**
