### PR TITLE
Added token authentication

### PR DESCRIPTION
**Pull request by silentninja**
Added Django Rest Framework token authentication.

I am not sure where to add the  usage info in read me.The mixin is to be used as follows:

1.Add the following to the settings file:
```python
SWAMP_DRAGON_CONNECTION = ('swampdragon_tokenauth.socketconnection.RemoteDataConnection', '/data')
```

2.Add the `TokenAuthMixin` to your router:

```python

from swampdragon_tokenauth.mixins import TokenAuthMixin
from swampdragon.route_handler import ModelRouter

# TokenAuthMixin should come before the model router

class TodoItemRouter(TokenAuthMixin,ModelRouter):
    route_name = 'todo-item'
    serializer_class = TodoItemSerializer
    model = TodoItem
    permission_classes = [LoginRequired()]

    def get_object(self, **kwargs):
        return self.model.objects.get(pk=kwargs['id'])

    def get_query_set(self, **kwargs):
        return self.model.objects.filter(todo_list__id=kwargs['list_id'])
```        

Pass in the drf auth token as 'auth' argument  when subscribing to a channel:

In angularjs:

```javascript
    $dragon.onReady(function() {
        $dragon.subscribe('todo-item', $scope.channel, {auth:"your_auth_token"}).then(function(response) {
            // code
        });
        })
```

### CODE REVIEW

**Comment by cancan101** [comment]
Be aware that the current token auth in DRF is in consideration for deprecation: https://github.com/tomchristie/django-rest-framework/issues/2644.

The right thing to use would be JWTs.

**Comment by silentninja** [comment]
My next work will be on jwt.I started with jwt but token auths are much simpler to use,So i started with that

**Comment by jonashagstedt** [comment]
@cancan101 It looks more like they are proposing JWT over the standard token auth but I don't think they would get rid of the current one.

@silentninja Great thinking! I like this.
I will give it a try in py2 and 3 before I merge it.

**Comment by cancan101** [comment]
Sure, I doubt they will get rid of the current but I and they think JWT is just an all around better choice.

**Comment by jpadilla** [comment]
Just clearing up, DRF's Token Authentication won't be deprecated any time soon.

**Pull request merged**
